### ISSUE TITLE
Support for multiple keys

### ISSUE THREAD

**Issue by jonnii** [erebus1/graphene-federation#11]
Apollo Federation supports [multiple primary keys](https://www.apollographql.com/docs/apollo-server/federation/advanced-features/#multiple-primary-keys). We could implement this in `graphene-federation` in one of two ways:

```
# Multiple key decorators
@key("id")
@key("username")
class Person(ObjectType):
    pass

# multiple keys in a single decorator
@key("id", "username")
class Person(ObjectType):
    pass
```

Can you let me know if you have a preference and I'll send a PR.

**Comment by jonnii** [comment]
@erebus1 I opened https://github.com/erebus1/graphene-federation/pull/12 just in case.

**Comment by erebus1** [comment]
merged
