### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bogdal** [erebus1/graphene-federation#13]
Hello. When do you plan to release a new version of this package? There have been several fixes since the last release and it would be great to see a new version on [PyPI](https://pypi.org/project/graphene-federation/).

**Comment by erebus1** [comment]
Hi
I'll publish a new version by the end of week

**Comment by bogdal** [comment]
Awesome. Many thanks 👍

**Comment by salwator** [comment]
@erebus1 sorry to bother you, is there any news regarding new package release?

**Comment by erebus1** [comment]
Sorry for the delay
Just published a new version
